DROP TABLE IF EXISTS S_USERS;
CREATE TABLE S_USERS
(
	user_id	INT PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(75),
	age INT,
);
DROP TABLE IF EXISTS S_GENRES;
CREATE TABLE S_GENRES
(
	genre_id	INT PRIMARY KEY AUTO_INCREMENT,
	genre_name  VARCHAR(75)
);
DROP TABLE IF EXISTS S_MOVIES;
CREATE TABLE S_MOVIES
(
	movie_id INT PRIMARY KEY AUTO_INCREMENT,
	movie_name VARCHAR(75),
	genre_id		INT,
	CONSTRAINT movies_fk FOREIGN KEY(genre_id) REFERENCES S_GENRES(genre_id)
);
DROP TABLE IF EXISTS S_MOVIE_RATINGS;
CREATE TABLE S_MOVIE_RATINGS
(
	movie_id	INT,
	user_id		INT,
	rating		INT,
	CONSTRAINT movie_ratings_pk PRIMARY KEY(movie_id,user_id),
	CONSTRAINT movie_id_fk FOREIGN KEY(movie_id) REFERENCES S_MOVIES(movie_id),
	CONSTRAINT users_id_fk FOREIGN KEY(user_id) REFERENCES S_USERS(user_id)
);
